name: 'Informatica Connection'
description: 'Composite of informatica connection'
inputs:
  connection_name:  # id of input
    description: 'Name of the connection to update'
    required: true
  az_creds:
    description: 'azure creds'
    required: true
  key_vault:
    description: 'Keyvault to use for target secrets'
    required: true



runs:
  using: "composite"
  steps:
        # Install python and dependent modules
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - uses: Azure/login@v1
        with:
          creds: ${{ inputs.az_creds }}

      - name: Install python modules
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - name: Get secrets
        shell: bash
        run: |
          echo "SECRET_LIST=$(az keyvault secret list --vault-name ${{ inputs.key_vault }} | \
          jq -r '.[] | select( .name | contains("${{ inputs.connection_name }}")) | .name ' | \
          paste -s -d, -)" >> $GITHUB_ENV

      - uses: Azure/get-keyvault-secrets@v1
        if: ${{ env.SECRET_LIST != '' }}
        with: 
          keyvault: ${{ inputs.key_vault }}
          secrets: ${{ env.SECRET_LIST }}
        id: retrieveConnectionSecrets

      - name: "Get Connection"
        shell: bash
        run: python3 ./scripts/promote_connection.py
        env:
          CONNECTION_NAME: ${{ inputs.connection_name }}