



name: 'Informatica Connection'
description: 'Composite of informatica connection'
inputs:
  connection_name:  # id of input
    description: 'Name of the connection to update'
    required: true
  secret_list: 
    description: 'List of KV secrets to be replaced'
    required: false
  az_creds:
    description: 'azure creds'
    required: true
runs:
  using: "composite"
  steps:
        # Install python and dependent modules
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - uses: Azure/login@v1
        with:
          creds: ${{ inputs.az_creds }}
      
      - name: Get secrets
        shell: bash
        run: echo "$(az keyvault secret list --vault-name psdekeyvault | jq -r '.[] | select( .name | contains("PS")) | .name ')"

      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "psdekeyvault"
          secrets: ${{ inputs.secret_list }}
        id: retrieveConnectionSecrets

      - name: "Get Connection"
        shell: bash
        run: python3 ./scripts/promote_connection.py ${{ inputs.connection_name }} ${{ inputs.secret_list }}