# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.

name: DEPLOY_CONNECTION
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      connection_name:
        description: "Connection Name"
        type: string
        required: true

env:
  IICS_LOGIN_URL: https://dm-us.informaticacloud.com
  IICS_POD_URL: https://na1.dm-us.informaticacloud.com/saas
 
  IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
  IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}

  UAT_IICS_USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
  UAT_IICS_PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}

  CONNECTION_NAME: ${{ github.event.inputs.connection_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_env:
    name: Setup Environment
    environment:
      name: development
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        connection: ["my_connection", "your_connection"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: ./.github/actions/connection
        with:
          connection_name: ${{ matrix.connection }}
          secret_list: "test-secret"
          az_creds: ${{ secrets.AZURE_CREDENTIALS }}